// Created by iWeb 3.0.3 local-build-20110628

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWPhotoFrame([IWCreateImage('31_B._Fultz,_et_al.,_DANSE__distributed_data_analysis_for_neutron_scattering_experiments,_http___danse.us_files/Creme_frame2_01.png'),IWCreateImage('31_B._Fultz,_et_al.,_DANSE__distributed_data_analysis_for_neutron_scattering_experiments,_http___danse.us_files/Creme_frame2_02.png'),IWCreateImage('31_B._Fultz,_et_al.,_DANSE__distributed_data_analysis_for_neutron_scattering_experiments,_http___danse.us_files/Creme_frame2_04.png'),IWCreateImage('31_B._Fultz,_et_al.,_DANSE__distributed_data_analysis_for_neutron_scattering_experiments,_http___danse.us_files/Creme_frame2_08.png'),IWCreateImage('31_B._Fultz,_et_al.,_DANSE__distributed_data_analysis_for_neutron_scattering_experiments,_http___danse.us_files/Creme_frame2_09.png'),IWCreateImage('31_B._Fultz,_et_al.,_DANSE__distributed_data_analysis_for_neutron_scattering_experiments,_http___danse.us_files/Creme_frame2_14.png'),IWCreateImage('31_B._Fultz,_et_al.,_DANSE__distributed_data_analysis_for_neutron_scattering_experiments,_http___danse.us_files/Creme_frame2_13.png'),IWCreateImage('31_B._Fultz,_et_al.,_DANSE__distributed_data_analysis_for_neutron_scattering_experiments,_http___danse.us_files/Creme_frame2_05.png')],null,0,1.000000,3.000000,3.000000,3.000000,3.000000,23.000000,23.000000,23.000000,23.000000,20.000000,19.000000,20.000000,19.000000,null,null,null,0.400000)});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('31_B._Fultz,_et_al.,_DANSE__distributed_data_analysis_for_neutron_scattering_experiments,_http___danse.us_files/31_B._Fultz,_et_al.,_DANSE__distributed_data_analysis_for_neutron_scattering_experiments,_http___danse.usMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');fixAllIEPNGs('../../../../Media/transparent.gif');Widget.onload();BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
