// Created by iWeb 3.0.3 local-build-20110628

setTransparentGifURL('../../../../Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWPhotoFrame([IWCreateImage('31_T._Kelley,_M._McKerns,_et_al.,_ARCS__software_for_a_wide_angle-range_chopper_spectrometer_at_the_SNS,_http___www.cacr.caltech.edu_projects_ARCS_Software.html_files/Creme_frame2_01.png'),IWCreateImage('31_T._Kelley,_M._McKerns,_et_al.,_ARCS__software_for_a_wide_angle-range_chopper_spectrometer_at_the_SNS,_http___www.cacr.caltech.edu_projects_ARCS_Software.html_files/Creme_frame2_02.png'),IWCreateImage('31_T._Kelley,_M._McKerns,_et_al.,_ARCS__software_for_a_wide_angle-range_chopper_spectrometer_at_the_SNS,_http___www.cacr.caltech.edu_projects_ARCS_Software.html_files/Creme_frame2_04.png'),IWCreateImage('31_T._Kelley,_M._McKerns,_et_al.,_ARCS__software_for_a_wide_angle-range_chopper_spectrometer_at_the_SNS,_http___www.cacr.caltech.edu_projects_ARCS_Software.html_files/Creme_frame2_08.png'),IWCreateImage('31_T._Kelley,_M._McKerns,_et_al.,_ARCS__software_for_a_wide_angle-range_chopper_spectrometer_at_the_SNS,_http___www.cacr.caltech.edu_projects_ARCS_Software.html_files/Creme_frame2_09.png'),IWCreateImage('31_T._Kelley,_M._McKerns,_et_al.,_ARCS__software_for_a_wide_angle-range_chopper_spectrometer_at_the_SNS,_http___www.cacr.caltech.edu_projects_ARCS_Software.html_files/Creme_frame2_14.png'),IWCreateImage('31_T._Kelley,_M._McKerns,_et_al.,_ARCS__software_for_a_wide_angle-range_chopper_spectrometer_at_the_SNS,_http___www.cacr.caltech.edu_projects_ARCS_Software.html_files/Creme_frame2_13.png'),IWCreateImage('31_T._Kelley,_M._McKerns,_et_al.,_ARCS__software_for_a_wide_angle-range_chopper_spectrometer_at_the_SNS,_http___www.cacr.caltech.edu_projects_ARCS_Software.html_files/Creme_frame2_05.png')],null,0,1.000000,3.000000,3.000000,3.000000,3.000000,23.000000,23.000000,23.000000,23.000000,20.000000,19.000000,20.000000,19.000000,null,null,null,0.400000)});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{dynamicallyPopulate();loadMozillaCSS('31_T._Kelley,_M._McKerns,_et_al.,_ARCS__software_for_a_wide_angle-range_chopper_spectrometer_at_the_SNS,_http___www.cacr.caltech.edu_projects_ARCS_Software.html_files/31_T._Kelley,_M._McKerns,_et_al.,_ARCS__software_for_a_wide_angle-range_chopper_spectrometer_at_the_SNS,_http___www.cacr.caltech.edu_projects_ARCS_Software.htmlMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');fixAllIEPNGs('../../../../Media/transparent.gif');Widget.onload();BlogFixupPreviousNext();applyEffects()}
function onPageUnload()
{Widget.onunload();}
